[config]
schemaVersion = "0.0.1"

[package]
namespace = "bitMods"
name = "SmarterHauling"
versionNumber = "1.0.0"
description = "Optimize how characters store and haul items; including telling characters to haul specific items to specific containers or racks."
websiteUrl = "https://github.com/bitMuse-Ostranauts/SmarterHauling"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Ostranauts = "5.4.2303"
bitMods-LaunchControl = "1.0.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./dist/thunderstore"

[[build.copy]]
source = "./artifact"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["ostranauts"]

[publish.categories]
ostranauts = ["mods"]


